version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka:1.1.0
    ports:
      - '9092-9094:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=${KAFKA_TOPIC}:${KAFKA_PARTITIONS:-3}:${KAFKA_REPLICATION_FACTOR:-1},${KAFKA_MIGRATION_TOPIC}:${KAFKA_PARTITIONS:-3}:${KAFKA_REPLICATION_FACTOR:-1}
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - HOSTNAME_COMMAND=route -n | awk '/UG[ \t]/{print $$2}'
      - KAFKA_ADVERTISED_HOST_NAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
